# Generated by Django 5.0.2 on 2024-03-10 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.TextField()),
                ('category_image_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ShopOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('isBlocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ShopOwners',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_license_number', models.CharField(max_length=50)),
                ('store_owner_name', models.CharField(max_length=50)),
                ('store_owner_contact', models.CharField(max_length=10)),
                ('store_rating', models.IntegerField(default=5)),
                ('store_desription', models.TextField()),
                ('store_image_url', models.TextField()),
                ('store_open_dates', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unique_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=10)),
                ('product_rating', models.IntegerField(default=5)),
                ('product_description', models.TextField()),
                ('product_image_url', models.TextField()),
                ('product_available', models.IntegerField(default=0)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100)),
                ('division_unique_id', models.IntegerField(default=0)),
                ('division_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
            options={
                'verbose_name_plural': 'division',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_contact_number', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(max_length=254)),
                ('belongs_to_the_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Advertisments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_unique_id', models.CharField(max_length=50)),
                ('ad_type', models.CharField(choices=[('banner', 'banner'), ('video', 'video')], max_length=50)),
                ('ad_url', models.TextField()),
                ('ad_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
        ),
    ]
