# Generated by Django 5.0.2 on 2024-03-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='division_store',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='belongs_to_the_store',
        ),
        migrations.RemoveField(
            model_name='advertisments',
            name='ad_store',
        ),
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
