# Generated by Django 5.0.2 on 2024-03-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisments',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
