# Generated by Django 5.0.2 on 2024-03-10 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_advertisments_delete_customers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_contact_number', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(max_length=254)),
                ('belongs_to_the_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
