# Generated by Django 5.0.2 on 2024-03-10 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.CreateModel(
            name='Advertisments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_unique_id', models.CharField(max_length=50)),
                ('ad_type', models.CharField(choices=[('banner', 'banner'), ('video', 'video')], max_length=50)),
                ('ad_url', models.TextField()),
                ('ad_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100)),
                ('division_unique_id', models.IntegerField(default=0)),
                ('division_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
            options={
                'verbose_name_plural': 'division',
            },
        ),
    ]
