# Generated by Django 5.0.2 on 2024-03-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_products_options_advertisments_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
