# Generated by Django 5.0.2 on 2024-03-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unique_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=10)),
                ('product_rating', models.IntegerField(default=5)),
                ('product_description', models.TextField()),
                ('product_image_url', models.TextField()),
                ('product_available', models.IntegerField(default=0)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('product_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.division')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
